config/routes.rb
Rails.application.routes.draw do

  root :to => "listings#index"

  devise_for :users
  resources :listings do
  	resources :orders, only: [:new, :create]
  end


  get 'seller' => 'listings#seller'
  get 'sales' => 'orders#sales'
  get 'purchases' => 'orders#purchases'
  

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	if Rails.env.development?
		has_attached_file 	:image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "Perfil.png"
	else
  	has_attached_file 	  :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "Perfil.png",
				    		          :storage => :dropbox,
    					           	:dropbox_credentials => Rails.root.join("config/dropbox.yml"),
    						          :path => ":style/:id_:filename"
  end
  	
    validates_attachment_presence :image
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
    validates :name, :price, :description, presence: true

    belongs_to :user
    has_many   :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
	validates :address, :city, :state, :country, presence: true

	belongs_to :listing
	belongs_to :buyer, class_name: "User"
	belongs_to :seller, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :listings, dependent: :destroy
  has_many :sellers, class_name: "Order", foreign_key: "seller_id"
  has_many :purchases, class_name: "Order", foreign_key: "buyer_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]



  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC") 
  end
  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Producto agregado satisfactoriamente!' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Producto modificado satisfactoriamente!' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Producto eliminado satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end

    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Lo sentimos, no tiene permisos suficientes"
      end
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end

  def purchases
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")
  end

  # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user

    @order.listing_id = @listing.id
    @order.buyer_id = current_user.id
    @order.seller_id = @seller.id

    respond_to do |format|
      if @order.save
        format.html { redirect_to :root, notice: 'Pedido generado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :state, :country)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Inicio', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links_devise' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Informaciones', page_path('about') %></li>
<li><%= link_to 'Contactos', page_path('contact') %></li>

app/views/layouts/_navigation_links_devise.html.erb
<% if user_signed_in? %>
	 <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Seller Account <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Administrar Productos', seller_path %></li>
            <li><%= link_to 'Sales History', sales_path %></li>
          </ul>
     </li>
     <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Purchases History', purchases_path %></li>
			<li><%= link_to 'Editar Perfil', edit_user_registration_path %></li>
			<li><%= link_to 'Cerrar Sesion', destroy_user_session_path, method: :delete %></li>
          </ul>
     </li>
	
<% else %>
	<li><%= link_to 'Registrarse', new_user_registration_path %></li>
	<li><%= link_to 'Iniciar Sesion', new_user_session_path %></li>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Lupe" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Lupe" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'https//js.stripe.com/v2' %>
    <%= csrf_meta_tags %>
    <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    
    <div class="container">
         <%= render 'layouts/messages' %>
         <%= yield %>
      
    </div>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing, :html => { :multipart => true }) do |f| %>
    <% if @listing.errors.any? %>
          <div class="alert alert-danger alert-dismissible">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4><%= pluralize(@listing.errors.count, "error") %> No se pudo guardar el registro:</h4>

          <ul>
          <% @listing.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
    <% end %>
  <div class="form-group">
    <%= f.label :name, "Nombre" %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description, "Descripcion" %><br>
    <%= f.text_area :description, class: "form-control", rows: "7" %>
  </div>
  <div class="form-group">
    <%= f.label :price, "Precio" %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image, "Imagen" %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editando elemento</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @listing, class: "btn btn-link" %> |
<%= link_to 'Atras', listings_path, class: "btn btn-link" %>

app/views/listings/index.html.erb
<div class="jumbotron">
  <h2>Encontra todo lo que buscas en un solo sitio!</h2>
  <h2>Ikela Comerce te ofrece descuentos especiales</h2>
</div>
<div class="center">
<div class="row">
  <% @listings.each do |listing| %>
  <div class="col-md-3">
      <div class="thumbnail">
      <%= link_to (image_tag listing.image.url(:medium)), listing %>
      <div class="caption">
        <h3><%= listing.name %></h3>
        <p><%= number_to_currency(listing.price) %></p>
        <p><%= "Ofrecido por: #{listing.user.name}" %></p>
      </div>
    </div>
       
  </div>
  <% end %> 
</div>
</div>
<br>

<% if user_signed_in? %>
  <%= link_to 'Nueva Fotito', new_listing_path, class: "btn btn-link" %>
<% end -%>

app/views/listings/new.html.erb
<h1>Agregando a la Lista</h1>

<%= render 'form' %>

<%= link_to 'Atras', listings_path, class: "btn btn-link" %>

app/views/listings/seller.html.erb
<table class="table table-hover table-condensed">
  <thead>
    <td class="center">Image</td>
    <td class="center">Name</td>
    <td class="center">Descripcion</td>
    <td class="center">Precio</td>
    <td class="center"></td>
  </thead>
    <% @listings.each do |listing| %>
  <tbody>
    <td class="center"><%= image_tag listing.image.url(:thumb) %></td>
    <td class="center"><%= listing.name %></td>
    <td class="center"><%= listing.description %></td>
    <td class="center"><%= number_to_currency(listing.price) %></td>
    <td class="center">
        <!-- Single button -->
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            Opciones <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li class="center"><%= link_to "Ver", listing, class: "btn btn-link" %></li>
            <li class="center"><%= link_to "Editar", edit_listing_path(listing), class: "btn btn-link" %></li>
            <li class="center"><%= link_to "Eliminar", listing, method: :delete, data: { confirm: "Estas seguro?"}, class: "btn btn-link" %></li>
          </ul>
        </div>
        
        
        
    </td>
  </tbody>
  <% end -%>

</table>




<br>

<% if user_signed_in? %>
  <%= link_to 'Nueva Fotito', new_listing_path, class: "btn btn-link" %>
<% end -%>

app/views/listings/show.html.erb
<div class="row">
	<div class="col-md-6">
		<div class="thumbnail">
			<%= image_tag @listing.image.url %>
		</div>
	</div>
	<div class="col-md-6">
		<h3><%= @listing.name %></h3>
		<p><%= number_to_currency(@listing.price) %></p>
		<p><%= @listing.description %></p>
		<br>
		<div class="center">
		<%= link_to "Comprar ahora", new_listing_order_path(@listing), class: "btn btn-primary" %>
		</div>
	</div>
</div>

<% if current_user == @listing.user %>
	<%= link_to 'Editar', edit_listing_path(@listing), class: "btn btn-link" %> |
<% end -%>
	<%= link_to 'Atras', listings_path, class: "btn btn-link" %>

app/views/orders/_form.html.erb
<div class="row">
  <div class="col-md-4">
      <div class="thumbnail">
        <%= image_tag @listing.image.url %>
        <h2 class="center"><%= @listing.name %></h2>
        <h4 class="center"><%= number_to_currency(@listing.price) %></h4>
      </div>
        
  </div>

<div class="col-md-8">

    <%= form_for([@listing, @order]) do |f| %>
      <% if @order.errors.any? %>
        <div class="alert alert-danger alert-dismissible">
              <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              
          <h3><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h3>

          <ul>
          <% @order.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :address %><br>
        <%= f.text_field :address, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :city %><br>
        <%= f.text_field :city, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :state %><br>
        <%= f.text_field :state, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :country %><br>
        <%= f.text_field :country, class: "form-control" %>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-md-8">
              <%= label_tag :card_number, 'Numero de Tarjeta de Credito' %><br>
              <%= text_field_tag :card_number, nil, {:name => nil, :'data-stripe' => "number", class: "form-control"} %>
          </div>
          <div class="col-md-4">
               <%= label_tag :card_code, 'CVC' %><br>
               <%= text_field_tag :card_code, nil,{:name => nil, :'data-stripe' => "cvc", class: "form-control"} %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag nil, "Expiration Date" %>
        <div class="row">
          <div class="col-md-3">
               <%= select_month nil, { use_two_digit_numbers: true}, {:name => nil, :'data-stripe' => 'exp-month', class: "form-control" } %>
          </div>
          <div class="col-md-3">
               <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+10}, {:name => nil, :'data-stripe' => 'exp-year', class: "form-control"} %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit "Generar pedido" , class: "btn btn-success"%>
      </div>
    <% end %>
</div>
</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.address %></td>
        <td><%= order.city %></td>
        <td><%= order.state %></td>
        <td><%= order.country %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<%= render 'form' %>

<%= link_to 'Atras', root_path %>

app/views/orders/purchases.html.erb
<div class="center">
<h2>Su historial de compras</h2>
</div>

<table class="table table-hover table-condensed">
  <thead>
    <td class="center">Image</td>
    <td class="center">Item</td>
    <td class="center">Price</td>
    <td class="center">Seller</td>
    <td class="center">Date Purchased</td>
    <td></td>
  </thead>
    <% @orders.each do |order| %>
  <tbody>
    <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
    <td class="center"><%= order.listing.name %></td>
    <td class="center"><%= number_to_currency(order.listing.price) %></td>
    <td class="center"><%= order.buyer.name %></td>
    <td class="center"><%= order.created_at.strftime("%d / %m / %y") %></td>

      </tbody>
  <% end -%>

</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'Nueva Fotito', new_listing_path, class: "btn btn-link" %>
<% end -%>

app/views/orders/sales.html.erb
<div class="center">
<h2>Su historial de ventas</h2>
</div>

<table class="table table-hover table-condensed">
  <thead>
    <td class="center">Image</td>
    <td class="center">Item</td>
    <td class="center">Price</td>
    <td class="center">Customer</td>
    <td class="center">Date Solc</td>
    <td></td>
  </thead>
    <% @orders.each do |order| %>
  <tbody>
    <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
    <td class="center"><%= order.listing.name %></td>
    <td class="center"><%= number_to_currency(order.listing.price) %></td>
    <td class="center"><%= order.buyer.name %></td>
    <td class="center"><%= order.created_at.strftime("%d / %m / %y") %></td>

      </tbody>
  <% end -%>

</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'Nueva Fotito', new_listing_path, class: "btn btn-link" %>
<% end -%>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @order.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @order.state %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/pages/about.html.erb
<% content_for :title do %>Sobre mi?<% end %>
<h3>Soy un sitio de prueba</h3>
<p>
Esta aplicacion fue desarrollada por kelecho

</p>

app/views/pages/contact.html.erb
<% content_for :title do %>Contactos<% end %>
<h3>Hacemos sistemas baratito</h3>
<p>
	David Barrios me debe todavia de la entrada a la libertadores
</p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>